BEGIN;

ALTER TABLE t_product_category ALTER COLUMN f_id SET GENERATED BY DEFAULT;
ALTER TABLE t_product_spu ALTER COLUMN f_id SET GENERATED BY DEFAULT;
ALTER TABLE t_product_sku ALTER COLUMN f_id SET GENERATED BY DEFAULT;

-- 产品分类根节点 (哨兵)
INSERT INTO t_product_category (f_id, f_public_uid, f_code, f_level, f_name) VALUES
  (-1, gen_random_uuid(), 'root', 0, '{"zh-CN":"根"}')
ON CONFLICT (f_id) DO NOTHING;

-- 产品分类
INSERT INTO t_product_category (f_id, f_public_uid, f_code, f_level, f_name) VALUES
  (1, gen_random_uuid(), 'handmade', 1, '{"zh-CN":"手作"}'),
  (2, gen_random_uuid(), 'necklace', 1, '{"zh-CN":"项链"}'),
  (3, gen_random_uuid(), 'toy', 1, '{"zh-CN":"玩具"}')
ON CONFLICT (f_code) DO UPDATE SET f_name = EXCLUDED.f_name;

INSERT INTO t_product_spu (f_id, f_public_uid, f_category_id, f_brand, f_name, f_description, f_meta_info) VALUES
(1, gen_random_uuid(), 1, '更懂它·知宠康乐', '{"zh-CN":"手作挂件 1"}', '{"zh-CN":"手作"}', '{"image_url":"https://dlvgbwyvxjdggxpddpod.supabase.co/storage/v1/object/public/gengdongta-assets/images/shop/handmade/WechatIMGb2313cba0db9517a8ad72b64effb6b06.jpg"}'),
(2, gen_random_uuid(), 1, '更懂它·知宠康乐', '{"zh-CN":"手作挂件 2"}', '{"zh-CN":"手作"}', '{"image_url":"https://dlvgbwyvxjdggxpddpod.supabase.co/storage/v1/object/public/gengdongta-assets/images/shop/handmade/WechatIMGf1d7b50e1dd753e6557847ce413eaba1.jpg"}'),
(3, gen_random_uuid(), 2, '更懂它·知宠康乐', '{"zh-CN":"水晶菩提象数本草智能项链"}', '{"zh-CN":"NFC智能项链"}', '{"image_url":"https://dlvgbwyvxjdggxpddpod.supabase.co/storage/v1/object/public/gengdongta-assets/images/shop/necklace/1/1.jpg"}'),
(4, gen_random_uuid(), 2, '更懂它·知宠康乐', '{"zh-CN":"本草智能项链硅胶扣款"}', '{"zh-CN":"NFC智能项链"}', '{"image_url":"https://dlvgbwyvxjdggxpddpod.supabase.co/storage/v1/object/public/gengdongta-assets/images/shop/necklace/2/1.jpg"}'),
(5, gen_random_uuid(), 2, '更懂它·知宠康乐', '{"zh-CN":"珍珠水晶本草智能项链"}', '{"zh-CN":"NFC智能项链"}', '{"image_url":"https://dlvgbwyvxjdggxpddpod.supabase.co/storage/v1/object/public/gengdongta-assets/images/shop/necklace/3/1.jpg"}'),
(6, gen_random_uuid(), 2, '更懂它·知宠康乐', '{"zh-CN":"水晶菩提硅胶带智能项链"}', '{"zh-CN":"NFC智能项链"}', '{"image_url":"https://dlvgbwyvxjdggxpddpod.supabase.co/storage/v1/object/public/gengdongta-assets/images/shop/necklace/4/1.jpg"}'),
(7, gen_random_uuid(), 2, '更懂它·知宠康乐', '{"zh-CN":"撞色硅胶本草智能项链"}', '{"zh-CN":"NFC智能项链"}', '{"image_url":"https://dlvgbwyvxjdggxpddpod.supabase.co/storage/v1/object/public/gengdongta-assets/images/shop/necklace/5/1.jpg"}'),
(8, gen_random_uuid(), 2, '更懂它·知宠康乐', '{"zh-CN":"菩提针织扣本草智能项链"}', '{"zh-CN":"NFC智能项链"}', '{"image_url":"https://dlvgbwyvxjdggxpddpod.supabase.co/storage/v1/object/public/gengdongta-assets/images/shop/necklace/6/1.jpg"}'),
(9, gen_random_uuid(), 2, '更懂它·知宠康乐', '{"zh-CN":"水晶菩提本草智能项链"}', '{"zh-CN":"NFC智能项链"}', '{"image_url":"https://dlvgbwyvxjdggxpddpod.supabase.co/storage/v1/object/public/gengdongta-assets/images/shop/necklace/7/1.jpg"}'),
(10, gen_random_uuid(), 2, '更懂它·知宠康乐', '{"zh-CN":"软香笼本草智能项圈"}', '{"zh-CN":"NFC智能项圈"}', '{"image_url":"https://dlvgbwyvxjdggxpddpod.supabase.co/storage/v1/object/public/gengdongta-assets/images/shop/necklace/8/1.jpg"}'),
(11, gen_random_uuid(), 2, '更懂它·知宠康乐', '{"zh-CN":"菩提本草智能项链"}', '{"zh-CN":"NFC智能项链"}', '{"image_url":"https://dlvgbwyvxjdggxpddpod.supabase.co/storage/v1/object/public/gengdongta-assets/images/shop/necklace/9/1.jpg"}'),
(12, gen_random_uuid(), 2, '更懂它·知宠康乐', '{"zh-CN":"菩提本草智能项圈"}', '{"zh-CN":"NFC智能项圈"}', '{"image_url":"https://dlvgbwyvxjdggxpddpod.supabase.co/storage/v1/object/public/gengdongta-assets/images/shop/necklace/10/1.jpg"}'),
(13, gen_random_uuid(), 3, '更懂它·知宠康乐', '{"zh-CN":"智能玩具"}', '{"zh-CN":"NFC智能玩具"}', '{"image_url":"https://dlvgbwyvxjdggxpddpod.supabase.co/storage/v1/object/public/gengdongta-assets/images/shop/toy/toy.jpg"}')
ON CONFLICT (f_id) DO NOTHING;

INSERT INTO t_product_sku (f_id, f_public_uid, f_spu_id, f_sku_code, f_price, f_currency) VALUES
(1, gen_random_uuid(), 1, 'SKU-HANDMADE-01', 49, 'CNY'),
(2, gen_random_uuid(), 2, 'SKU-HANDMADE-02', 49, 'CNY'),
(3, gen_random_uuid(), 3, 'SKU-NECKLACE-03', 68, 'CNY'),
(4, gen_random_uuid(), 4, 'SKU-NECKLACE-04', 68, 'CNY'),
(5, gen_random_uuid(), 5, 'SKU-NECKLACE-05', 68, 'CNY'),
(6, gen_random_uuid(), 6, 'SKU-NECKLACE-06', 68, 'CNY'),
(7, gen_random_uuid(), 7, 'SKU-NECKLACE-07', 68, 'CNY'),
(8, gen_random_uuid(), 8, 'SKU-NECKLACE-08', 68, 'CNY'),
(9, gen_random_uuid(), 9, 'SKU-NECKLACE-09', 68, 'CNY'),
(10, gen_random_uuid(), 10, 'SKU-NECKLACE-10', 68, 'CNY'),
(11, gen_random_uuid(), 11, 'SKU-NECKLACE-11', 68, 'CNY'),
(12, gen_random_uuid(), 12, 'SKU-NECKLACE-12', 68, 'CNY'),
(13, gen_random_uuid(), 13, 'SKU-TOY-13', 29, 'CNY')
ON CONFLICT (f_sku_code) DO UPDATE SET f_price = EXCLUDED.f_price;

ALTER TABLE t_product_category ALTER COLUMN f_id SET GENERATED ALWAYS;
ALTER TABLE t_product_spu ALTER COLUMN f_id SET GENERATED ALWAYS;
ALTER TABLE t_product_sku ALTER COLUMN f_id SET GENERATED ALWAYS;

SELECT setval('t_product_category_f_id_seq', GREATEST(COALESCE((SELECT MAX(f_id) FROM t_product_category WHERE f_id > 0), 0), 10));
SELECT setval('t_product_spu_f_id_seq', GREATEST(COALESCE((SELECT MAX(f_id) FROM t_product_spu), 0), 20));
SELECT setval('t_product_sku_f_id_seq', GREATEST(COALESCE((SELECT MAX(f_id) FROM t_product_sku), 0), 20));

COMMIT;
